### ISSUE TITLE
Class Permissions Not Found when using Tinker

### ISSUE THREAD

**Issue by RhysLees** [tpg/deadbolt#22]
PHP Warning:  Class "Permissions" not found in C:\Users\TEMC0\OneDrive\Desktop\HubV3\vendor\laravel\framework\src\Illuminate\Foundation\AliasLoader.php on line 80

**Comment by RhysLees** [comment]
I fixed it by adding  'Permissions' => TPG\Deadbolt\Facades\Deadbolt::class, to aliases

**Comment by warrickbayman** [comment]
Thanks for picking it up. I'll merge a fix today.

**Comment by warrickbayman** [comment]
Fixed in v2.0.2. Let me know if you still have issues.
