### ISSUE TITLE
Need Help in using it with Inertia

### ISSUE THREAD

**Issue by abbasmashaddy72** [tpg/deadbolt#24]
Hi, @warrickbayman

I had liked your project, it is very good and easy to use.

I want to use this in my inertia application which I just got started, can you please me out with how to integrate it with Jetstream inertia and use it in the Vue templates.

**Comment by warrickbayman** [comment]
Hey @abbasmashaddy72. So Deadbolt doesn't really do anything as far as your JS is concerned. It's a PHP library after all. However, permissions are stored as JSON on your user, so just pass your user as a property when you render your Inertia view:

```php
return Inertia::render('Home', [
    'user' => Auth::user(),
]);
```

You could add this to your `HandleInertiaRequests` middleware if you'd rather. Then, from your Vue component, you can check if a permission exists with something like:

```javascript
const canEdit = props.user.permissions.includes('articles.edit');
```

If you're using version 2.1.0 then I've included a really simple JavaScript helper that gives you some tools to test for permissions so you don't have to do it yourself. It's in the README: https://github.com/tpg/deadbolt#javascript-helper

Then you can do this:

```javascript
const permissions = new Deadbolt(props.user);
const canEdit = permissions.has('articles.edit');
```

The JavaScript helper is experimental, but you shouldn't have any major problems. Let me know if you get stuck.

**Comment by abbasmashaddy72** [comment]
I am using Vue 3 If there is any doubt I will let you know.

Thanks for the reply.

**Comment by abbasmashaddy72** [comment]
Hi, @warrickbayman 
Thanks to the update, I was successfully able to implement it in inertia, but I need a small help how can I add roles to certain permission.

I am okay with both static and dynamic method.

**Comment by warrickbayman** [comment]
@abbasmashaddy72 Deadbolt doesn't have a roles solution built in. The idea was to keep it simple, and roles over complicate things. You probably shouldn't be authorising against roles anyway. However, there's a simple guide on implementing your own roles with Deadbolt: https://github.com/tpg/deadbolt/wiki/2.-Roles. It hasn't been updated in a while, but the idea is still the same.

**Comment by abbasmashaddy72** [comment]
Thanks for the reply.
@warrickbayman 

I am not authorizing any users based on roles, but only to keep it user-friendly I want to add some default permission to certain roles.

**Comment by warrickbayman** [comment]
@abbasmashaddy72  Okay, cool. The model you pass to the `Deadbolt::user()` method doesn't have to be an actual `User` model. It could be a `Role` model. I've used Deadbolt in exactly that way once or twice.

Glad you're finding it useful.

**Comment by abbasmashaddy72** [comment]
Thanks for the Help.
@warrickbayman 

It helped me a lot as permission is the most precised part in any project.

**Comment by abbasmashaddy72** [comment]
Hi
@warrickbayman 

I am unable to use @can in blade after giving users the permissions in users table.

Should I define the gate, or is there anything else I have to do?

It will be great to have a project that you created as a reference to use the permissions.

**Comment by warrickbayman** [comment]
Hi @abbasmashaddy72. You need to create Laravel policy classes to use `@can`.  There's some info in the README.

**Comment by abbasmashaddy72** [comment]
And how can I define Gate in Controllers


@warrickbayman

**Comment by warrickbayman** [comment]
Hi @abbasmashaddy72. Did you come right?

**Comment by Zaheer-94** [comment]
how to make read permissions in deadbolt.php from file or cache 
I am unable to use @can in blade as I'm passing data to deadbolt.php in array fromat from cache file
